# code: language=ansible
---
- name: Stat link {{ item.dest }}
  ansible.builtin.stat:
    path: "{{ item.dest }}"
  register: stat_link

- name: Ensure link directory exists {{ item.dest | dirname }}
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    state: directory
  become: "{{ item.sudo | default(omit) }}"

- name: Create secret file link {{ item.dest }}
  ansible.builtin.file:
    src: "{{ secret_files_path }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ target_user.username | default(ansible_user_id) }}"
    mode: "{{ item.permissions | default(secret_files_link_permissions) }}"
    force: "{{ item.force | default(false) }}"
    state: link
  become: "{{ item.sudo | default(omit) }}"
  when: not stat_link.stat.exists or item.force | default(false)