# code: language=ansible
---
- name: Get status of fish feature {{ item.name }}
  stat:
    path: "{{ fish_config_dir }}/{{ item.name }}.fish"
  register: stat_result

- name: Enable fish feature {{ item.name }}
  ansible.builtin.template:
    src: "features/{{ item.name }}.fish.j2"
    dest: "{{ fish_config_dir }}/{{ item.name }}.fish"
    mode: '0644'
  when:
    - item.state == 'present'
    - not stat_result.stat.exists
  vars:
    ansible_callback_diy_runner_on_skipped_msg: |
      skipping: [{{ inventory_hostname }}] => msg: Fish feature already exists
    ansible_callback_diy_runner_on_skipped_msg_color: cyan
