# code: language=ansible
---

- name: Enable fish feature {{ item.name }}
  ansible.builtin.template:
    src: "features/{{ item.name }}.fish.j2"
    dest: "{{ fish_config_dir }}/{{ item.name }}.fish"
    mode: '0644'
  when: item.state == 'present'
