# code: language=ansible
---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_terminal: yes
configure_macos: yes
configure_vscode: yes
configure_secret_files: no

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL


# dotfiles_repo: https://github.com/db-it/dotfiles.git
dotfiles_repo: git@github.com:db-it/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
# dotfiles_repo_local_destination: ~/development/github/dotfiles
dotfiles_repo_local_destination: ~/workspace/personal/dotfiles
dotfiles_files:
  - .gitignore
  - .gitconfig
  - .macos

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - asimov # TimeMachine dev exclusions https://github.com/stevegrunwell/asimov
  - fish
  - jq
  - ncdu
  - tree
  - vim
  - wget
  - yq
  - z
  # dev
  - atlassian/tap/atlassian-plugin-sdk
  - git
  - git-lfs

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  # are these needed? Check this in future.
  # - homebrew/cask-fonts
  # - homebrew/cask-versions
  - adoptopenjdk/openjdk
  - atlassian/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  ### common ###
  # - appcleaner
  - aerial
  - arc
  - bettertouchtool
  - betterzip
  # - coconutbattery
  - dropbox
  - enpass
  - firefox
  - gimp
  - go2shell
  - google-chrome
  # open source video transcoder
  # - handbrake
  - iterm2
  - itsycal
  # Animated screen capture application
  # - licecap
  - nextcloud
  - qlcolorcode
  - qlmarkdown
  - qlprettypatch
  - qlstephen
  - qlvideo
  - quicklook-json
  - suspicious-package
  - webpquicklook
  # File transfer applications
  # - transmit
  - vlc
  # - vmware-fusion

  ### employer related ##
  - viscosity
  
  ### dev ##
  - jetbrains-toolbox
  - docker
  - google-cloud-sdk
  - temurin11
  - temurin17
  - visual-studio-code
  - wireshark

vscode_user_config:
  - username: "{{ target_user }}"
    visual_studio_code_extensions: []
    # Overwrite the settings file if it exists. Options: boolean "yes" or "no" (defaults to "no").
    visual_studio_code_settings_overwrite: no
    visual_studio_code_settings: {} # JSON object
    # Overwrite the keybindings file if it exists. Options: boolean "yes" or "no" (defaults to "no").
    visual_studio_code_keybindings_overwrite: no
    visual_studio_code_keybindings: [] # JSON array

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

macos_script: "~/.macos --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
