# code: language=ansible
---
# Variables that can be overwritten by the user

fisher_plugins: []

fish_feature_config:
  - name: fnm
    state: present
  - name: gcloudsdk
    state: present
  - name: homebrew
    state: present
  - name: java
    state: present
    version: 11
  - name: nvm
    state: absent
  - name: pyenv
    state: present
  - name: vscode
    state: present

fish_state: present
fisher_state: present

fish_set_default_shell: false


fish_shell_path: >-
  {% if ansible_facts['os_family'] == 'Darwin' and ansible_facts['architecture'] == 'x86_64' %}
  /usr/local/bin/fish
  {% elif ansible_facts['os_family'] == 'Darwin' and ansible_facts['architecture'] == 'arm64' %}
  /opt/homebrew/bin/fish
  {% else %}
  /usr/bin/fish
  {% endif %}

fish_role_dependency_packages:
  - curl # curl is required for fisher installation

fish_config_path: "{{ target_user.user_dir }}/.config/fish"
fish_config_dir: "{{ fish_config_path }}/conf.d"

fisher_path: "{{ target_user.user_dir }}/.config/fisher"
fisher_path_config_filename: fisher_path.fish

fisher_function_file: "{{ target_user.user_dir }}/.config/fish/functions/fisher.fish"
fisher_fish_plugins_file: "{{ target_user.user_dir }}/.config/fish/fish_plugins"

target_user:
  username: "{{ ansible_user_id }}"
  user_dir: "{{ ansible_user_dir }}"
