# code: language=ansible
---
secret_files_path: "{{ ansible_env.HOME }}/.secrets"

secret_files_links: []
# Example:
# - src: .netrc
#   dest: ~/.netrc
#   force: true           # default: N/A
#   permissions: '0644'   # default: {{ secret_files_link_permissions }}
#   sudo: true            # default: N/A

secret_files_link_permissions: '0600'