# code: language=ansible
---
- name: See if Dock item {{ item.name | default(item) }} exists
  ansible.builtin.command: "{{ dockutil_bin }} --find '{{ item.name }}'"
  register: dockitem_exists
  failed_when: >
    "No such file or directory" in dockitem_exists.stdout
    or "command not found" in dockitem_exists.stdout
  changed_when: false
  tags: ['dock']

- name: Get current dock section from output
  set_fact:
    current_section: "{{ dockitem_exists.stdout | regex_replace('^.*was found in (.*) at slot.*$', '\\1') }}"
  when: dockitem_exists.rc == 0
  tags: ['dock']

- name: Ensure Dock item {{ item.name | default(item) }} exists
  ansible.builtin.command: "{{ dockutil_bin }} --add '{{ item.path }}' --label '{{ item.name }}' --no-restart"
  when: dockitem_exists.rc >0 or
        dockitem_exists.rc == 0 and current_section == 'recent-apps'
  tags: ['dock']
