# code: language=ansible
---

# The package name to install
visual_studio_code_package: "visual-studio-{{ (visual_studio_code_build == 'insiders') | ternary('code-insiders', 'code') }}"

# The name of the directory where the config is stored for this build
visual_studio_code_config_dirname: "{{ (visual_studio_code_build == 'insiders') | ternary('Code - Insiders', 'Code') }}"

# Directory under $HOME where where VS Code config is stored
# On MacOS it's: ~/Library/Application Support/Code
# else (Linux) it's: ~/.config/Code
visual_studio_code_config_path: "{{ ansible_env.HOME }}/{{ (ansible_distribution == 'MacOSX') | ternary('Library/Application Support', '.config') }}/{{ visual_studio_code_config_dirname }}"
