# code: language=ansible
---
- name: Ensure pyenv is present
  ansible.builtin.package:
    name: pyenv
    state: "{{ pyenv_state }}"

- name: Configure shell integration
  ansible.builtin.template:
    src: "{{ pyenv_shell_environment_file }}.j2"
    dest: "{{ pyenv_shell_config_dir }}/{{ pyenv_shell_environment_file }}"

- name: Install Python version
  ansible.builtin.command:
    cmd: pyenv install --skip-existing {{ item }}
