# code: language=ansible
---
- name: Is path a directory
  local_action:
    module: ansible.builtin.stat
    path: "{{ path_item }}"
  register: sync_path

- name: Ensure path exists {{ path_item | dirname }}
  ansible.builtin.file:
    path: "{{ path_item | dirname }}"
    state: directory

- name: Sync directory {{ path_item }}
  ansible.posix.synchronize:
    src: "{{ path_item }}"
    dest: "{{ path_item | dirname }}"
  when: sync_path.stat.isdir


- name: Sync file {{ path_item }}
  ansible.posix.synchronize:
    src: "{{ path_item }}"
    dest: "{{ path_item }}"
  when: sync_path.stat.isreg
