# code: language=ansible
---
- name: Debug backup paths
  debug:
    msg: "Copy {{ path_item }} to {{ backup_and_restore_paths_backup_path }}/{{ path_item | dirname }}"

# this is theoretically only required if path_item is a file (because of ansible.builtin.copy behaviour)
- name: Create path in backup destination {{ path_item | dirname }}
  ansible.builtin.file:
    path: "{{ backup_and_restore_paths_backup_path }}/{{ path_item | dirname }}"
    state: directory

- name: Backup path {{ path_item }}
  ansible.builtin.copy:
    src: "{{ path_item }}"
    dest: "{{ backup_and_restore_paths_backup_path }}/{{ path_item | dirname }}"
