# code: language=ansible
---
- name: Find files to backup {{ path_item }}
  ansible.builtin.find:
    paths: "{{ path_item | dirname }}"
    patterns: "{{ path_item | basename }}"
    file_type: "any"
  register: files_to_copy

- name: Print found files for pattern {{ path_item }}
  debug:
    msg: "{{ files_to_copy['files'] | map(attribute='path') }}"

# this is theoretically only required if path_item is a file (because of ansible.builtin.copy behaviour)
- name: Create path in backup destination {{ path_item | dirname }}
  # This: {{ path_item | dirname }} makes ~/Library/Services from ~/Library/Services/d12r*
  ansible.builtin.file:
    path: "{{ backup_and_restore_paths_backup_path }}/{{ path_item | dirname }}"
    state: directory

- name: Backup files in path {{ path_item }}
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ backup_and_restore_paths_backup_path }}/{{ path_item | dirname }}"
  loop: "{{ files_to_copy['files'] | map(attribute='path') }}"
