# code: language=ansible
---
- name: Include backup glob path
  ansible.builtin.include_tasks: backup-glob-path.yml
  when: '"*" in path_item'

- name: Include backup path
  ansible.builtin.include_tasks: backup-path.yml
  # args:
  #   apply:
  #     tags: ['backup_and_restore_paths_do_backup']
  when: '"*" not in path_item'