# code: language=ansible
---
pyenv_state: present

pyenv_python_versions:
  - 3.11.4


shell_integration_file: pyenv.fish

# TODO: detect this automatically on host
shell_config_dir: "{{ ansible_user_dir }}/.config/fish/conf.d"