# code: language=ansible
---
- name: Assert supported package manager
  ansible.builtin.assert:
    that:
      - "ansible_pkg_mgr in ('homebrew')"

- name: Include tasks install-{{ ansible_pkg_mgr }}
  include_tasks: install-{{ ansible_pkg_mgr }}.yml
